# -*- coding: utf-8 -*-
"""HW3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Rv3jFTjK9AzmJVB_XTmGoXZiu8ZPrQyP
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
Boston = pd.read_csv('/content/drive/MyDrive/MLDL/Boston.csv')
Boston

"""##(a)

"""

import numpy as np
mu = np.mean(Boston['medv'])
print(mu)

"""##(b)"""

std_error = np.std(Boston['medv'])/np.sqrt(len(Boston['medv']))
print(std_error)

"""##(c)"""

means = []

for _ in range(10000):
  boot_sample = Boston.sample(n=len(Boston), replace=True)
  boot_mean = np.mean(boot_sample['medv'])
  means.append(boot_mean)

print(np.mean(means))
print(np.std(means))

"""##(d)"""

SE = np.std(means)
print(mu-2*SE, mu+2*SE)

std = Boston['medv'].std() / np.sqrt(len(Boston['medv']))
print(mu-2*std, mu+2*std)

"""##(e)"""

medv_median = Boston['medv'].median()
print(medv_median)

"""##(f)

"""

medians = []

for _ in range(10000):
  boot_sample = Boston.sample(n=len(Boston), replace=True)
  boot_median = np.median(boot_sample['medv'])
  medians.append(boot_median)

print(np.std(medians))

"""##(g)"""

print(np.percentile(Boston['medv'], 10))

"""##(h)"""

percentile = []

for _ in range(10000):
  boot_sample = Boston.sample(n=len(Boston), replace=True)
  boot_percentile = np.percentile(boot_sample['medv'], 10)
  percentile.append(boot_percentile)

print(np.std(percentile))